"""Pydantic schemas."""
from app.schemas.user import UserCreate, UserLogin, UserResponse, Token
from app.schemas.bank_connection import BankConnectionCreate, BankConnectionResponse
from app.schemas.account import AccountResponse
from app.schemas.transaction import TransactionResponse, TransactionFilter
from app.schemas.category import CategoryResponse
from app.schemas.budget import BudgetCreate, BudgetResponse
from app.schemas.goal import GoalCreate, GoalResponse, GoalUpdate
from app.schemas.bank_product import BankProductResponse
from app.schemas.recommendation import RecommendationResponse
from app.schemas.consent import (
    ConsentRequestCreate,
    ConsentRequestResponse,
    ConsentDecisionRequest,
    ConsentResponse,
    ConsentEventResponse,
    ConsentListResponse,
    PartnerBankResponse,
)
from app.schemas.payment import (
    PaymentCreate,
    PaymentResponse,
    InterbankTransferCreate,
    InterbankTransferResponse,
    InterbankTransferStatusUpdate,
    InternalTransferRequest,
    InternalTransferResponse,
)
from app.schemas.product_agreement import (
    ProductAgreementCreate,
    ProductAgreementSign,
    ProductAgreementResponse,
    ProductAgreementWithSchedule,
    PaymentScheduleResponse,
    AgreementEventResponse,
    AgreementListResponse,
    MakePaymentRequest,
    AgreementCloseRequest,
)
from app.schemas.family import (
    FamilyCreate,
    FamilyInviteResponse,
    FamilyResponse,
    FamilyDetailResponse,
    FamilyJoinRequest,
    FamilyMemberUpdateRequest,
    FamilyMemberResponse,
    FamilyBudgetCreate,
    FamilyBudgetResponse,
    FamilyMemberLimitCreate,
    FamilyMemberLimitResponse,
    FamilyGoalCreate,
    FamilyGoalResponse,
    FamilyGoalContributionCreate,
    FamilyGoalContributionResponse,
    FamilyTransferCreate,
    FamilyTransferApproveRequest,
    FamilyTransferResponse,
    FamilyNotificationResponse,
    FamilyAnalyticsSummary,
    AccountVisibilityUpdate,
    FamilyDashboardResponse,
)

__all__ = [
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "Token",
    "BankConnectionCreate",
    "BankConnectionResponse",
    "AccountResponse",
    "TransactionResponse",
    "TransactionFilter",
    "CategoryResponse",
    "BudgetCreate",
    "BudgetResponse",
    "GoalCreate",
    "GoalResponse",
    "GoalUpdate",
    "BankProductResponse",
    "RecommendationResponse",
    "ConsentRequestCreate",
    "ConsentRequestResponse",
    "ConsentDecisionRequest",
    "ConsentResponse",
    "ConsentEventResponse",
    "ConsentListResponse",
    "PartnerBankResponse",
    "PaymentCreate",
    "PaymentResponse",
    "InterbankTransferCreate",
    "InterbankTransferResponse",
    "InterbankTransferStatusUpdate",
    "InternalTransferRequest",
    "InternalTransferResponse",
    "ProductAgreementCreate",
    "ProductAgreementSign",
    "ProductAgreementResponse",
    "ProductAgreementWithSchedule",
    "PaymentScheduleResponse",
    "AgreementEventResponse",
    "AgreementListResponse",
    "MakePaymentRequest",
    "AgreementCloseRequest",
    "FamilyCreate",
    "FamilyInviteResponse",
    "FamilyResponse",
    "FamilyDetailResponse",
    "FamilyJoinRequest",
    "FamilyMemberUpdateRequest",
    "FamilyMemberResponse",
    "FamilyBudgetCreate",
    "FamilyBudgetResponse",
    "FamilyMemberLimitCreate",
    "FamilyMemberLimitResponse",
    "FamilyGoalCreate",
    "FamilyGoalResponse",
    "FamilyGoalContributionCreate",
    "FamilyGoalContributionResponse",
    "FamilyTransferCreate",
    "FamilyTransferApproveRequest",
    "FamilyTransferResponse",
    "FamilyNotificationResponse",
    "FamilyAnalyticsSummary",
    "AccountVisibilityUpdate",
    "FamilyDashboardResponse",
]

